version: "3.9"

services:
  database:
    container_name: postgrate
    environment:
      POSTGRES_USER: s-admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database1
    image: postgres
    networks:
      - main
    ports:
      - 5405:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    container_name: web
    build: .
    ports:
      - "5000:5000"
    networks:
      - main
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server

  nginx:
    container_name: nginx
    restart: always
    build: .
    ports:
      - "10080:80"
      - "10443:443"
    networks:
      - main
    depends_on:
      - app

networks:
  main: